name: Deploy GitHub Pages

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/**
      - src/**
      - package-lock.json
      - package.json

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4.2.1
      - name: Setup Node.js v20.12.0
        uses: actions/setup-node@v4.0.4
        with:
          node-version: 20.12.0
          cache: npm
      - name: Install dependent npm modules
        run: npm install
      - name: Compile source files
        run: ../../node_modules/.bin/tsc
        working-directory: ./src/ts
      - name: Remove source files
        run: rm -rf ./src/ts
      - name: Upload page artifact
        uses: actions/upload-pages-artifact@v3.0.1
        with:
          path: src/

  deploy:
    runs-on: ubuntu-latest
    needs: compile
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
      id-token: write
    steps:
      - name: Deploy GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4.0.5